#==========================  Modules configuration ============================
metricbeat.modules:
- module: system
  metricsets:
    - "cpu"
    - "diskio"
    - "memory"
    - "network"
#    - "core"
    - "filesystem"
    - "fsstat"
    - "load"
    - "process"
    - "process_summary"
    - "raid"
    - "socket"
    - "socket_summary"
    - "uptime"
  cpu.metrics: ["percentages"]
  hosts: []
  period: 10s
  enabled: true
#================================ General =====================================
fields:
  logzio_codec: json
  type: host-metrics-collector
fields_under_root: true
#================================ Outputs =====================================
output.logstash:
  hosts: []
  ssl.certificate_authorities: ['/etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt']
